import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { getFriendProfiles, searchProfiles } from "@/lib/social/queries";
import { ResolveFriendButton, SendFriendButton } from "@/components/social/friend-action-form";
import { CountryFlag, ProfileAvatar } from "@/components/media/media";
import { EmptyState, PageHeader, SectionLabel } from "@/components/ui/primitives";

type FriendsPageProps = { searchParams: Promise<{ q?: string }> };

export default async function FriendsPage({ searchParams }: FriendsPageProps) { const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login"); const { q = "" } = await searchParams; const [groups, results] = await Promise.all([getFriendProfiles(supabase, user.id), q ? searchProfiles(supabase, user.id, q) : Promise.resolve([])]); return <div className="app-content-inner"><PageHeader eyebrow="Social" title="Find your rivals." description="Add friends, accept requests, and compare calls once the match begins." action={<Link className="text-sm font-bold text-[var(--lime)]" href={{ pathname: "/leaderboard", query: { scope: "friends" } }}>Friends table ↗</Link>} /><form className="mt-7 flex gap-3" method="get"><label className="sr-only" htmlFor="friend-search">Search people</label><input className="min-h-12 min-w-0 flex-1 rounded-xl border border-[var(--line)] bg-[var(--surface-1)] px-4 text-sm text-[var(--text)] placeholder:text-[var(--text-faint)]" id="friend-search" name="q" defaultValue={q} placeholder="Search username or display name" /><button className="min-h-12 rounded-xl bg-[var(--lime)] px-5 text-sm font-bold text-[var(--canvas)] hover:bg-[var(--lime-strong)]" type="submit">Search</button></form>{q && <section className="mt-8"><SectionLabel>Search results</SectionLabel><div className="mt-4 grid gap-3 md:grid-cols-2">{results.length ? results.map((profile) => <div className="surface flex items-center justify-between gap-4 rounded-xl p-4" key={profile.id}><Identity profile={profile} />{profile.relationship === "none" && <SendFriendButton profileId={profile.id} />}{profile.relationship === "outgoing" && <span className="text-xs font-bold text-[var(--text-muted)]">Request pending</span>}{profile.relationship === "incoming" && <ResolveFriendButton friendshipId={profile.friendshipId!} action="accept" label="Accept" />}{profile.relationship === "friend" && <span className="text-xs font-bold text-[var(--success)]">Friends</span>}{profile.relationship === "blocked" && <span className="text-xs text-[var(--text-muted)]">Blocked</span>}</div>) : <EmptyState title="No one matched" description={`No searchable profiles matched “${q}”. Try a username or display name.`} />}</div></section>}<div className="mt-12 grid gap-8 lg:grid-cols-3"><FriendGroup title="Requests to respond to" profiles={groups.incoming} action="accept" actionLabel="Accept" secondaryAction="reject" secondaryLabel="Reject" /><FriendGroup title="Your rivals" profiles={groups.friends} action="remove" actionLabel="Remove" secondaryAction="block" secondaryLabel="Block" /><FriendGroup title="Sent requests" profiles={groups.outgoing} action="cancel" actionLabel="Cancel" /></div></div>; }

function Identity({ profile }: { profile: { display_name: string; username: string | null; avatar_url: string | null; country_code: string | null } }) { return <div className="flex min-w-0 items-center gap-3"><ProfileAvatar name={profile.display_name} avatarUrl={profile.avatar_url} /><div className="min-w-0"><p className="truncate font-bold">{profile.display_name}</p><p className="mt-1 flex items-center gap-2 text-xs text-[var(--text-muted)]">{profile.username ? `@${profile.username}` : "New predictor"}{profile.country_code ? <CountryFlag countryCode={profile.country_code} label={`${profile.display_name}'s country`} /> : null}</p></div></div>; }

function FriendGroup({ title, profiles, action, actionLabel, secondaryAction, secondaryLabel }: { title: string; profiles: Awaited<ReturnType<typeof getFriendProfiles>>["friends"]; action: "accept" | "remove" | "cancel"; actionLabel: string; secondaryAction?: "reject" | "block"; secondaryLabel?: string }) { return <section><SectionLabel>{title}</SectionLabel><div className="mt-4 space-y-3">{profiles.length ? profiles.map((profile) => <div className="surface rounded-xl p-4" key={profile.friendshipId}><Identity profile={profile} /><div className="mt-4 flex flex-wrap gap-2"><ResolveFriendButton friendshipId={profile.friendshipId} action={action} label={actionLabel} />{secondaryAction && <ResolveFriendButton friendshipId={profile.friendshipId} action={secondaryAction} label={secondaryLabel!} />}</div></div>) : <div className="rounded-xl border border-dashed border-[var(--line)] px-4 py-8 text-center text-sm text-[var(--text-faint)]">Nothing here yet.</div>}</div></section>; }
