"use client";

import { useActionState } from "react";
import { saveProfile, type ProfileFormState } from "@/app/(app)/profile/profile-actions";
import type { SelectableTeam } from "@/lib/profiles/queries";
import { CountryFlag, TeamCrest } from "@/components/media/media";

const initialState: ProfileFormState = { ok: true, message: "" };

export function ProfileForm({ teams, profile, mode, next }: { teams: SelectableTeam[]; profile: { username: string | null; display_name: string; favorite_team_id: string | null; country_code: string | null; bio: string | null; is_searchable: boolean; profile_visibility: "public" | "friends" | "private" }; mode: "onboarding" | "edit"; next?: string }) {
  const [state, formAction, isPending] = useActionState(saveProfile, initialState);
  const selectedTeam = teams.find((team) => team.id === profile.favorite_team_id);
  return <form action={formAction} className="mt-8 space-y-8">
    <input name="next" type="hidden" value={next ?? ""} />
    <input name="mode" type="hidden" value={mode} />
    <div className="grid gap-5 sm:grid-cols-2">
      <label className="block text-sm font-bold">Username<span className="ml-1 text-[var(--lime)]">*</span><span className="mt-1 block text-xs font-normal text-[var(--text-muted)]">Your unique matchday handle.</span><input name="username" defaultValue={profile.username ?? ""} autoComplete="username" className="mt-3 w-full rounded-xl border border-[var(--line)] bg-[var(--surface-2)] px-4 py-3 text-[var(--text)] placeholder:text-[var(--text-faint)]" placeholder="your_handle" required />{state.fieldErrors?.username?.map((error) => <span className="mt-2 block text-xs font-bold text-[var(--danger)]" key={error}>{error}</span>)}</label>
      <label className="block text-sm font-bold">Display name<span className="ml-1 text-[var(--lime)]">*</span><span className="mt-1 block text-xs font-normal text-[var(--text-muted)]">The name friends see on leaderboards.</span><input name="displayName" defaultValue={profile.display_name === "New predictor" ? "" : profile.display_name} autoComplete="nickname" className="mt-3 w-full rounded-xl border border-[var(--line)] bg-[var(--surface-2)] px-4 py-3 text-[var(--text)] placeholder:text-[var(--text-faint)]" placeholder="Ayaan" required />{state.fieldErrors?.displayName?.map((error) => <span className="mt-2 block text-xs font-bold text-[var(--danger)]" key={error}>{error}</span>)}</label>
    </div>
    <fieldset><legend className="text-sm font-bold">Choose your team<span className="ml-1 text-[var(--lime)]">*</span></legend><p className="mt-1 text-xs text-[var(--text-muted)]">Your crest appears beside your calls.</p><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{teams.map((team) => <label className="cursor-pointer" key={team.id}><input className="peer sr-only" type="radio" name="favoriteTeamId" value={team.id} defaultChecked={team.id === profile.favorite_team_id} required /><span className="flex min-h-24 flex-col justify-between rounded-xl border border-[var(--line)] bg-[var(--surface-2)] p-4 transition hover:border-[var(--lime)] peer-checked:border-[var(--lime)] peer-checked:bg-[var(--lime)] peer-checked:text-[var(--canvas)] peer-focus-visible:ring-2 peer-focus-visible:ring-[var(--lime)]"><span className="flex items-center justify-between gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-[var(--canvas)] text-xs font-black text-[var(--lime)]">{team.code?.slice(0, 2) ?? team.name.slice(0, 2).toUpperCase()}</span><span className="text-xs font-black uppercase tracking-[0.12em] opacity-70">{team.code ?? "TEAM"}</span></span><span className="mt-3 text-sm font-black">{team.short_name || team.name}</span></span></label>)}</div>{state.fieldErrors?.favoriteTeamId?.map((error) => <span className="mt-2 block text-xs font-bold text-[var(--danger)]" key={error}>{error}</span>)}</fieldset>
    {mode === "edit" && <details className="rounded-2xl border border-[var(--line)] bg-[var(--background)] p-5"><summary className="cursor-pointer text-sm font-black">More profile details</summary><div className="mt-5 grid gap-5 sm:grid-cols-2"><label className="block text-sm font-bold">Country code<input name="countryCode" defaultValue={profile.country_code ?? ""} className="mt-2 w-full rounded-xl border border-[var(--line)] bg-[var(--surface)] px-4 py-3" placeholder="PK" /></label><label className="block text-sm font-bold">Profile visibility<select name="profileVisibility" defaultValue={profile.profile_visibility} className="mt-2 w-full rounded-xl border border-[var(--line)] bg-[var(--surface)] px-4 py-3"><option value="public">Public</option><option value="friends">Friends only</option><option value="private">Private</option></select></label><label className="block text-sm font-bold sm:col-span-2">Bio<textarea name="bio" defaultValue={profile.bio ?? ""} className="mt-2 min-h-28 w-full resize-y rounded-xl border border-[var(--line)] bg-[var(--surface)] px-4 py-3" maxLength={280} placeholder="What kind of call do you make?" /></label><label className="flex items-center gap-3 text-sm font-bold sm:col-span-2"><input name="isSearchable" type="checkbox" defaultChecked={profile.is_searchable} className="h-5 w-5 accent-[var(--dark)]" />Let people find me by username</label></div></details>}
    {state.message && <p className={state.ok ? "rounded-2xl bg-[var(--accent)] px-4 py-3 text-sm font-bold" : "rounded-2xl bg-red-50 px-4 py-3 text-sm font-bold text-red-700"} role="status">{state.message}</p>}
    <button className="inline-flex w-full items-center justify-center rounded-2xl bg-[var(--dark)] px-5 py-4 font-black text-white transition hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-50 sm:w-auto" disabled={isPending} type="submit">{isPending ? "Saving your details..." : mode === "onboarding" ? "Enter the matchday" : "Save profile"}</button>
    {selectedTeam && mode === "edit" && <p className="flex items-center gap-2 text-sm text-[var(--muted)]">Current crest: <TeamCrest name={selectedTeam.name} code={selectedTeam.code} badgeUrl={selectedTeam.badge_url} size={24} /><span className="font-bold text-[var(--foreground)]">{selectedTeam.name}</span><CountryFlag countryCode={selectedTeam.country_code} label={selectedTeam.name} /></p>}
  </form>;
}
