import Link from "next/link";
import { redirect } from "next/navigation";
import { generateFriendsInsight } from "@/app/(app)/insights/actions";
import { InsightPanel } from "@/components/ai/insight-panel";
import { LeaderboardTable } from "@/components/social/leaderboard-table";
import { getLeaderboard, type LeaderboardScope } from "@/lib/leaderboards/queries";
import { getLatestSummary } from "@/lib/ai/summary-service";
import { createClient } from "@/lib/supabase/server";
import { PageHeader, SectionLabel } from "@/components/ui/primitives";

type LeaderboardPageProps = { searchParams: Promise<{ scope?: string }> };
export default async function LeaderboardPage({ searchParams }: LeaderboardPageProps) { const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login"); const { scope: requestedScope } = await searchParams; const scope: LeaderboardScope = requestedScope === "friends" ? "friends" : "global"; const [rows, insight] = await Promise.all([getLeaderboard(supabase, scope), getLatestSummary(supabase, user.id, "friends_recap")]); return <div className="app-content-inner"><PageHeader eyebrow="The table" title="Who called it best?" description="A record built from scored matches, exact calls, and deterministic tie-breakers." action={<Link className="text-sm font-bold text-[var(--lime)]" href="/friends">Manage friends ↗</Link>} /><div className="mt-7 inline-flex rounded-xl border border-[var(--line)] bg-[var(--surface-1)] p-1" aria-label="Leaderboard scope"><Link className={`rounded-lg px-5 py-2.5 text-sm font-bold ${scope === "global" ? "bg-[var(--lime)] text-[var(--canvas)]" : "text-[var(--text-muted)]"}`} href={{ pathname: "/leaderboard", query: { scope: "global" } }}>Global</Link><Link className={`rounded-lg px-5 py-2.5 text-sm font-bold ${scope === "friends" ? "bg-[var(--lime)] text-[var(--canvas)]" : "text-[var(--text-muted)]"}`} href={{ pathname: "/leaderboard", query: { scope: "friends" } }}>Friends</Link></div>{scope === "friends" && <div className="mt-7"><InsightPanel action={generateFriendsInsight} canGenerate={Boolean(process.env.GEMINI_API_KEY) && rows.length > 1} description="A grounded read of accepted-friend standings and momentum." initialSummary={insight?.content ?? null} title="Friends table briefing" /></div>}<div className="mt-8 flex items-end justify-between"><div><SectionLabel>Verified standings</SectionLabel><h2 className="font-display mt-2 text-3xl font-bold">Current ranking</h2></div><span className="text-xs font-bold text-[var(--text-faint)]">{rows.length} predictors</span></div><div className="mt-4"><LeaderboardTable rows={rows} currentUserId={user.id} /></div></div>; }
