import type { LeaderboardRow } from "@/lib/leaderboards/queries";
import { CountryFlag, ProfileAvatar, TeamCrest } from "@/components/media/media";
import { EmptyState } from "@/components/ui/primitives";

export function LeaderboardTable({ rows, currentUserId }: { rows: LeaderboardRow[]; currentUserId: string }) {
  if (!rows.length) return <EmptyState title="The table is waiting" description="Make the first call and this is where your points, rank, and Called It record will appear." />;
  return <div className="overflow-hidden rounded-2xl border border-[var(--line)] bg-[var(--surface-1)]"><div className="hidden grid-cols-[76px_1fr_repeat(4,110px)] gap-4 border-b border-[var(--line)] bg-[var(--surface-2)] px-6 py-4 text-[10px] font-bold uppercase tracking-[0.14em] text-[var(--text-faint)] md:grid"><span>Rank</span><span>Predictor</span><span>Points</span><span>Exact</span><span>Called It</span><span>Streak</span></div><div className="divide-y divide-[var(--line)]">{rows.map((row) => <div className={`grid gap-3 px-5 py-4 md:grid-cols-[76px_1fr_repeat(4,110px)] md:items-center md:gap-4 md:px-6 ${row.user_id === currentUserId ? "border-l-2 border-[var(--lime)] bg-[var(--lime)]/10" : ""}`} key={row.user_id}><div className="font-display text-3xl font-bold text-[var(--lime)]">#{row.rank}</div><div className="flex min-w-0 items-center gap-3"><ProfileAvatar name={row.display_name} avatarUrl={row.avatar_url} size={38} /><div className="min-w-0"><p className="truncate font-bold">{row.display_name}{row.user_id === currentUserId ? <span className="ml-2 text-xs font-bold text-[var(--lime)]">You</span> : null}</p><p className="mt-1 flex flex-wrap items-center gap-2 text-xs text-[var(--text-muted)]">{row.username ? `@${row.username}` : "New predictor"}{row.favorite_team_name ? <><span aria-hidden="true">·</span>{row.favorite_team_badge_url ? <TeamCrest name={row.favorite_team_name} badgeUrl={row.favorite_team_badge_url} size={18} /> : null}{row.favorite_team_name}</> : null}{row.country_code ? <CountryFlag countryCode={row.country_code} label={`${row.display_name}'s country`} /> : null}</p></div></div><Value label="Points" value={row.total_points} /><Value label="Exact" value={row.exact_scores} /><Value label="Called It" value={row.called_it_cards} /><Value label="Streak" value={row.current_streak} /></div>)}</div></div>;
}

function Value({ label, value }: { label: string; value: number }) { return <div><span className="text-[10px] font-bold uppercase tracking-[0.1em] text-[var(--text-faint)] md:hidden">{label} · </span><strong className="font-display text-2xl font-bold">{value}</strong></div>; }
