import { PredictionForm } from "@/components/matches/prediction-form";
import { MatchStatus } from "@/components/matches/match-status";
import type { MatchDetailViewModel, MatchSummaryViewModel } from "@/lib/matches/queries";
import { CountryFlag, TeamCrest } from "@/components/media/media";
import { LocalTime } from "@/components/ui/local-time";

export function MatchCard({ match }: { match: MatchSummaryViewModel | MatchDetailViewModel }) {
  const isFinished = match.status === "finished";
  return <article className="ticket-surface ticket-rail interactive-lift overflow-hidden rounded-2xl p-5 pt-8 sm:p-6 sm:pt-9"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.17em] text-[var(--lime)]">{match.stage}</p><p className="mt-1 text-xs text-[var(--text-faint)]">{match.status === "scheduled" ? <LocalTime date={match.kickoffAt} mode="match" /> : match.status === "live" ? "Live now" : match.status === "finished" ? "Final whistle" : match.status}</p></div><span className="font-display text-xl font-bold text-[var(--text-muted)]">{match.status === "scheduled" ? "CALL" : isFinished ? "RESULT" : "UPDATE"}</span></div><div className="mt-8 grid grid-cols-[1fr_auto_1fr] items-center gap-3 text-center"><TeamName team={match.homeTeam} /><div>{isFinished ? <p className="font-display text-5xl font-bold leading-none tracking-[-0.03em] text-[var(--text)]">{match.homeScore}–{match.awayScore}</p> : match.status === "postponed" ? <p className="font-display text-2xl font-bold text-[var(--warning)]">TBD</p> : match.status === "cancelled" ? <p className="font-display text-2xl font-bold text-[var(--danger)]">OFF</p> : <p className="font-display text-2xl font-bold text-[var(--text-faint)]">VS</p>}</div><TeamName team={match.awayTeam} /></div>{match.status === "scheduled" && <PredictionForm match={match} />}{match.status === "live" && <p className="mt-6 rounded-xl border border-[var(--live)]/30 bg-[var(--live)]/10 px-4 py-3 text-center text-sm font-bold text-[var(--live)]">Predictions are locked while this match is live.</p>}{isFinished && match.prediction && <p className="mt-6 rounded-xl border border-[var(--line)] bg-[var(--surface-2)] px-4 py-3 text-center text-sm font-bold">Your call: {match.prediction.predicted_home_score}–{match.prediction.predicted_away_score} <span className="ml-1 text-[var(--lime)]">· {match.prediction.confidence_multiplier}×</span></p>}<MatchStatus match={match} /></article>;
}

function TeamName({ team }: { team: MatchSummaryViewModel["homeTeam"] }) { return <div className="min-w-0"><TeamCrest name={team.name} code={team.code} badgeUrl={team.badge_url} size={44} className="mx-auto" /><p className="mt-3 truncate text-sm font-bold leading-tight sm:text-base">{team.name}</p><span className="mt-1 inline-flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-[0.15em] text-[var(--text-faint)]"><CountryFlag countryCode={team.country_code} label={team.name} />{team.code ?? "TEAM"}</span></div>; }
